
complete -xc viman -a "(__fish_complete_man)"

complete -xc viman -a 1 --description "Program section"
complete -xc viman -a 2 --description "Syscall section"
complete -xc viman -a 3 --description "Library section"
complete -xc viman -a 4 --description "Device section"
complete -xc viman -a 5 --description "File format section"
complete -xc viman -a 6 --description "Games section"
complete -xc viman -a 7 --description "Misc section"
complete -xc viman -a 8 --description "Admin section"
complete -xc viman -a 9 --description "Kernel section"
complete -xc viman -a tcl --description "Tcl section"
complete -xc viman -a n --description "New section"
complete -xc viman -a l --description "Local section"
complete -xc viman -a p
complete -xc viman -a o --description "Old section"
complete -rc viman -s C --description "Configuration file"
complete -xc viman -s M -a "(__fish_complete_directories (commandline -ct))" --description "Manpath"
complete -rc viman -s P --description "Pager"
complete -xc viman -s S --description "Manual sections"
complete -c viman -s a --description "Display all matches"
complete -c viman -s c --description "Always reformat"
complete -c viman -s d --description "Debug"
complete -c viman -s D --description "Debug and run"
complete -c viman -s f --description "Show whatis information"
complete -c viman -s F -l preformat --description "Format only"
complete -c viman -s h --description "Display help and exit"
complete -c viman -s k --description "Show apropos information"
complete -c viman -s K --description "Search in all man pages"
complete -xc viman -s m --description "Set system"
complete -xc viman -s p --description "Preprocessors"
complete -c viman -s t --description "Format for printing"
complete -c viman -s w -l path --description "Only print locations"
complete -c viman -s W --description "Only print locations"

